version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: gotalk-dictation
    goos: [linux]
    goarch: [amd64]
    ldflags:
      - -s -w
      - -X github.com/Alijeyrad/gotalk-dictation/internal/version.Version={{ .Version }}
      - -X github.com/Alijeyrad/gotalk-dictation/internal/version.Commit={{ .ShortCommit }}
    flags:
      - -trimpath

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - install.sh
      - packaging/com.alijeyrad.GoTalkDictation.desktop
      - packaging/com.alijeyrad.GoTalkDictation.metainfo.xml
      - internal/ui/assets/icon.png

nfpms:
  - id: packages
    package_name: gotalk-dictation
    vendor: Alijeyrad
    homepage: https://github.com/Alijeyrad/gotalk-dictation
    maintainer: Ali Julaee Rad
    description: System-wide speech-to-text dictation for X11
    license: MIT
    formats:
      - deb
      - rpm
    dependencies: []
    contents:
      - src: packaging/com.alijeyrad.GoTalkDictation.desktop
        dst: /usr/share/applications/com.alijeyrad.GoTalkDictation.desktop
      - src: packaging/com.alijeyrad.GoTalkDictation.metainfo.xml
        dst: /usr/share/metainfo/com.alijeyrad.GoTalkDictation.metainfo.xml

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: Alijeyrad
    name: gotalk-dictation
  draft: false
  prerelease: auto
  extra_files:
    - glob: install.sh
